name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install root deps
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Install backend deps
        working-directory: backend
        run: npm ci

      - name: Test backend
        working-directory: backend
        env:
          JWT_SECRET: ci_secret
        run: npm run test:ci
