name: Build and Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]
 
# Grant write permissions so the GITHUB_TOKEN can push to the `gh-pages` branch
permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Check required envs
        env:
          VITE_API_BASE: ${{ secrets.RENDER_BACKEND_URL }}
        run: |
          if [ -z "${VITE_API_BASE}" ]; then
            echo "ERROR: required secret RENDER_BACKEND_URL (VITE_API_BASE) is not set. Set repository secret 'RENDER_BACKEND_URL' to your backend base URL (e.g. https://api.example.com/api)" >&2
            exit 1
          fi

      - name: Build
        env:
          # VITE_BASE is optional; ./ works for most GH Pages setups.
          VITE_BASE: './'
          # Set this secret in your repository to the backend base URL, e.g. https://api-yourservice.onrender.com
          VITE_API_BASE: ${{ secrets.RENDER_BACKEND_URL }}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          allow_empty_commit: true
          commit_message: "chore: deploy frontend to gh-pages [skip ci]"
          user_name: "github-actions[bot]"
          user_email: "41898282+github-actions[bot]@users.noreply.github.com"
